# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: setup Python
         env:
          PYTHONPATH: ./BE
        uses: actions/checkout@v2
        with:
          python-version: "3.9"

      - name: install dependies
        run: pip install -r BE/requirements.txt

      - name: install Rest api
        run: python BE/calculator.py --rest &

      - name: run pytest
        run: pytest --junit-xml=report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"

      - uses: actions/checkout@v4

      - name: login to azure registery
        uses: docker/login-action@v3
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      - name: Run and build docker image
        run: docker build --push --tag judevops.azurecr.io/nasir_jama_elmi-calculator BE/
